spring.application.name=dms

spring.datasource.url = jdbc:mysql://localhost:3306/iskconbsl
spring.datasource.username = root
spring.datasource.password = root
spring.datasource.driver = com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=YnI0YTN6NHI1dDZ5N3U4aTlvMHAxbTJtM240YjV2NmM3eDg=

# 2. Make it readable
spring.jpa.properties.hibernate.format_sql=true

# 3. Add comments to explain which JPA method triggered the SQL
spring.jpa.properties.hibernate.use_sql_comments=true

# 4. Show the actual values being sent to the DB
logging.level.org.hibernate.orm.jdbc.bind=trace
